query GetPairs {
    allEvents(condition: {contract: "con_pairs", event: "PairCreated"}) {
        edges {
            node {
                dataIndexed
                data
            }
        }
    }
}